# Generated by Django 4.2.6 on 2023-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_keyword_name_alter_trend_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trend',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.TextField(),
        ),
    ]
